# Generated by Django 3.0.8 on 2020-07-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimientoFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comentario', models.CharField(max_length=1000)),
                ('categoria_movimiento_financiero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CategoriaMovimientoFinanciero')),
            ],
        ),
    ]
