# Generated by Django 3.0.8 on 2020-07-29 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200728_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 0, 44, 27, 697420, tzinfo=utc)),
        ),
    ]
