# Generated by Django 3.1.5 on 2021-01-28 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200729_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(default='NZD', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 4, 59, 43, 357580, tzinfo=utc)),
        ),
    ]
