# Generated by Django 3.1.5 on 2021-01-28 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210129_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriamovimientofinanciero',
            old_name='tipo_movimiento_financiero',
            new_name='tipo_categoria_movimiento_financiero',
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 22, 3, 45, 235323, tzinfo=utc)),
        ),
    ]
